url: "https://haokunliu.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "刘昊琨 Haokun Liu" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-seo-tag

# Optional: Additional SEO settings
description: "Haokun Liu's personal website"
author:
  name: "刘昊琨 Haokun Liu"
social:
  name: Haokun Liu
  links:
    - https://x.com/HaokunLiu5280
    - https://bsky.app/profile/haokunliu.bsky.social
