url: "https://haokunliu.com/" 
baseurl: "" 
title: "刘昊琨 Haokun Liu" 
sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag


description: "Haokun Liu's Homepage"
author:
  name: "刘昊琨 Haokun Liu"
social:
  name: Haokun Liu
  links:
    - https://x.com/HaokunLiu5280
    - https://bsky.app/profile/haokunliu.bsky.social
