menu:
- {name: 'publications', url: '/publications'}
# - {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/laoliu5280'}
- {icon: 'twitter', link: 'https://x.com/HaokunLiu5280'}
- {icon: 'email', link: 'mailto:haokunliu@uchicago.edu'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Mr. Haokun Liu', title: 'Ph.D. Student', department: 'Computer Science', institution: 'University of Chicago', institution_address: '5735 S Ellis Ave', email: 'haokunliu@uchicago.edu', office: 'Searle 207'}
